insert into institutions (name) values ('Stoltenberg and Sons');
insert into institutions (name) values ('Murphy-Feest');
insert into institutions (name) values ('Goyette Inc');
insert into institutions (name) values ('Beatty LLC');
insert into institutions (name) values ('Grimes-Labadie');
insert into institutions (name) values ('DuBuque-Effertz');
insert into institutions (name) values ('Reinger Group');
insert into institutions (name) values ('Rutherford, Hermiston and Haag');
insert into institutions (name) values ('Hyatt, Shanahan and Wisoky');
insert into institutions (name) values ('Strosin LLC');
insert into institutions (name) values ('Powlowski LLC');
insert into institutions (name) values ('Hodkiewicz LLC');
insert into institutions (name) values ('Bartoletti LLC');
insert into institutions (name) values ('Runolfsdottir Inc');
insert into institutions (name) values ('Bechtelar, Harvey and Schumm');
insert into institutions (name) values ('Marks-Gleason');
insert into institutions (name) values ('Lockman LLC');
insert into institutions (name) values ('Hudson Group');
insert into institutions (name) values ('Corkery, Quigley and Gerlach');
insert into institutions (name) values ('Ullrich-Gleichner');
insert into institutions (name) values ('Hauck and Sons');
insert into institutions (name) values ('Heathcote-Brekke');
insert into institutions (name) values ('Kemmer-Jacobi');
insert into institutions (name) values ('Bergnaum and Sons');
insert into institutions (name) values ('Anderson LLC');
insert into institutions (name) values ('Brown-Christiansen');
insert into institutions (name) values ('Hansen-Armstrong');
insert into institutions (name) values ('Wiegand-McLaughlin');
insert into institutions (name) values ('Lueilwitz Inc');
insert into institutions (name) values ('Veum, O''Kon and Farrell');
insert into institutions (name) values ('Watsica-Schinner');
insert into institutions (name) values ('Ratke, Willms and Prohaska');
insert into institutions (name) values ('Schroeder, Dicki and Heidenreich');
insert into institutions (name) values ('Schiller, Hagenes and Wolff');
insert into institutions (name) values ('Nolan and Sons');
insert into institutions (name) values ('Gorczany Inc');
insert into institutions (name) values ('Green, Mohr and Leannon');
insert into institutions (name) values ('Kreiger, Becker and Considine');
insert into institutions (name) values ('Rolfson-Sanford');
insert into institutions (name) values ('Kris-Bartoletti');
insert into institutions (name) values ('Pollich Inc');
insert into institutions (name) values ('Mueller-Mante');
insert into institutions (name) values ('Nienow, Crist and Gleichner');
insert into institutions (name) values ('Eichmann, Cremin and Hane');
insert into institutions (name) values ('Waelchi LLC');
insert into institutions (name) values ('Tremblay Group');
insert into institutions (name) values ('Gerhold LLC');
insert into institutions (name) values ('Krajcik-Gerlach');
insert into institutions (name) values ('Swaniawski-Littel');
insert into institutions (name) values ('Ritchie LLC');
insert into institutions (name) values ('Boehm-Konopelski');
insert into institutions (name) values ('Larson, Lebsack and Mohr');
insert into institutions (name) values ('Schuster-Ryan');
insert into institutions (name) values ('D''Amore, Connelly and Bins');
insert into institutions (name) values ('Botsford and Sons');
insert into institutions (name) values ('Reichel and Sons');
insert into institutions (name) values ('Wolff, Cummerata and Torp');
insert into institutions (name) values ('Feil Inc');
insert into institutions (name) values ('Nikolaus-Gutkowski');
insert into institutions (name) values ('Dicki Inc');
insert into institutions (name) values ('Larson and Sons');
insert into institutions (name) values ('Price-Waters');
insert into institutions (name) values ('Wilderman, Deckow and Gleason');
insert into institutions (name) values ('Medhurst, Mante and Wilkinson');
insert into institutions (name) values ('Tromp-Raynor');
insert into institutions (name) values ('Schumm, Welch and Gerlach');
insert into institutions (name) values ('Howell, Boehm and Little');
insert into institutions (name) values ('Howell Group');
insert into institutions (name) values ('Heathcote, Schmidt and Smith');
insert into institutions (name) values ('Hirthe LLC');
insert into institutions (name) values ('Sipes Group');
insert into institutions (name) values ('Muller-Lebsack');
insert into institutions (name) values ('King-Littel');
insert into institutions (name) values ('Bins, Murphy and Little');
insert into institutions (name) values ('Jenkins, Nitzsche and Reinger');
insert into institutions (name) values ('Goodwin-Koepp');
insert into institutions (name) values ('Hickle Group');
insert into institutions (name) values ('Morar, Batz and Collier');
insert into institutions (name) values ('Torp Group');
insert into institutions (name) values ('Schuster-Dickinson');
insert into institutions (name) values ('Maggio-Hirthe');
insert into institutions (name) values ('Goyette Group');
insert into institutions (name) values ('Kassulke, Zieme and Monahan');
insert into institutions (name) values ('Goldner and Sons');
insert into institutions (name) values ('Yost and Sons');
insert into institutions (name) values ('Parker Group');
insert into institutions (name) values ('Brakus-Aufderhar');
insert into institutions (name) values ('Schowalter, Carter and Homenick');
insert into institutions (name) values ('Brakus, Langosh and King');
insert into institutions (name) values ('Grant-Doyle');
insert into institutions (name) values ('Armstrong-Purdy');
insert into institutions (name) values ('Dickinson-Corkery');
insert into institutions (name) values ('Klein, Braun and Becker');
insert into institutions (name) values ('Goldner, Kuhic and O''Hara');
insert into institutions (name) values ('Walter LLC');
insert into institutions (name) values ('Abernathy Inc');
insert into institutions (name) values ('Rempel, Mosciski and Larkin');
insert into institutions (name) values ('Beier-Dare');
insert into institutions (name) values ('Friesen, Schuster and Rice');
insert into institutions (name) values ('Berge Inc');
